version: '2'
services:
  ms_notifications_db:
    image:  mongo:3.0.14
    command: mongod --smallfiles  --quiet
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    ports:
      - "4003:27017"
    expose:
      - "4003"
  ms_notifications:
    build: .
    ports:
      - "3003:3000"
    volumes:
      - '.:/app'
    command: bash -c " rm -f tmp/pids/server.pid && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - ms_notifications_db
