version: '2'
services:
  ms_notifications_db:
   image: mongo:latest
   container_name: "rancher-node1"

   environment:
    - MONGO_DATA_DIR=/data/db
   
   volumes:
    - ./data/db:/data/db
   ports:
     - "4007:4007"
   command: mongod --smallfiles  --profile 2  # --quiet

  ms_notifications:
   build: .
   command: bash -c " rm -f tmp/pids/server.pid && bundle
    exec rails db:migrate && bundle exec rails s -p 3007 -b '0.0.0.0'"
   ports:
    - "3007:3007"
   depends_on:
    - ms_notifications_db
