version: '2'
services:
  ms_notifications_db:
   image:  mongo:3.0.14
   command: mongod --smallfiles  --quiet
   environment:
    - RAILS_ENV=production
    - RACK_ENV=production
   
   ports:
     - "4007:27017"
   

  ms_notifications:
   depends_on:
     - ms_notifications_db
   build: .   
   ports:
    - "3007:3007"
   volumes: 
      - '.:/app'
   command: bash -c " rm -f tmp/pids/server.pid && bundle
    exec rails db:migrate && bundle exec rails s -p 3007 -b '0.0.0.0'"

volumes:
  ms_notifications_db: